services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/lindsay/.config/appdata/npm:/data
      - /home/lindsay/.config/appdata/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "npmdb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    depends_on:
      - npmdb
 
  npmdb:
    image: 'jc21/mariadb-aria:latest'
    container_name: npmdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - /home/lindsay/.config/appdata/npmdb:/var/lib/mysql
      
  nginx:
    image: nginx:1-alpine
    container_name: www
    ports:
      - 8089:80
    volumes:
      - /media/v/vm/www/:/usr/share/nginx/html
      
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    hostname: duplicati
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/New_York
    ports:
      - "8200:8200"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lindsay/.config/appdata:/config/appdata
      - /home/lindsay/storage:/storage
      - /home/lindsay/.docker/:/docker
      - /media/f/:/media/f/
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    environment:
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
      ServerIP: 0.0.0.0
      TZ: America/New_York
      WEBPASSWORD: ""
    ports:
      - "446:443"
      - "8008:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lindsay/.config/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /home/lindsay/.config/appdata/pihole/pihole:/etc/pihole
      - /home/lindsay/storage:/storage
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  watchtower:
    container_name: watchtower
    image: ghcr.io/containrrr/watchtower:latest
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      TZ: America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lindsay/storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    hostname: wireguard
    environment:
      ALLOWEDIPS: 0.0.0.0/0
      INTERNAL_SUBNET: 10.13.13.0
      SERVERURL: jupiterns.org
      PEERS: s22,chromebook,laptop
      PEERDNS: auto
      PGID: "1000"
      PUID: "1000"
      TZ: America/New_York
      SERVERPORT: "51820"
    ports:
      - "51820:51820/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /lib/modules:/lib/modules
      - /home/lindsay/.config/appdata/wireguard:/config
      - /home/lindsay/storage:/storage
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"