services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "${TZ}"
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - /etc:/etc-backup:rw
      - /media/f:/media/f:rw
      - /home/${USERNAME}:/home/${USERNAME}:rw
      - ${APPDATA_PATH}/duplicati:/config
      - /home/${USERNAME}/storage:/storage

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      PUID: 1000
      GUID: 1000
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "https://music.jupiterns.org"
    volumes:
      - "/home/{USERNAME}/.config/appdata/navidrome:/data"
      - "/media/d/music/music_lindsay/:/music:ro"
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment: 
      TZ: "${TZ}"
      PUID: "1000"
      PGID: "1000"
    restart: always
    ports:
      - "9696:9696"
    volumes:
      - /media/d:/media/d:rw
      - /media/e:/media/e:rw
      - ${APPDATA_PATH}/prowlarr:/config
      - /home/${USERNAME}/storage:/storage
  
#  audiobookshelf:
#    image: ghcr.io/advplyr/audiobookshelf:latest
#    container_name: audiobookshelf
#    ports:
#      - 13378:80
#    volumes:
#      - /media/e/audiobooks:/audiobooks
#      - /media/e/_currently_sorting:/audiobooks_sorting
#      - /media/e/books:/books
#      - /media/e/_currently_sorting:/books_sorting
#      - /home/lindsay/.podcasts:/podcasts
#      - ${APPDATA_PATH}/audiobookshelf/config:/config
#      - ${APPDATA_PATH}/audiobookshelf/meta:/metadata
#    environment:
#      TZ: "${TZ}"
#      PUID: "1000"
#      PGID: "1000"
#    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment: 
      TZ: "${TZ}"
      WEBUI_PORT: "25000"
      PUID: "1000"
      PGID: "1000"
    restart: always
    ports:
      - "51413:51413/tcp"
      - "51413:51413/udp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "25000:25000"
    volumes:
      - /media/d:/media/d:rw
      - /media/e:/media/e:rw
      - /media/f:/media/f:rw
      - /media/e/_downloads/._downloading:/downloading:rw
      - /media/e/_currently_sorting:/sorting:rw
      - /media/e/_downloads:/downloads:rw
      - ${APPDATA_PATH}/qbittorrent:/config
      - /home/${USERNAME}/storage:/storage

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: 
      TZ: "${TZ}"
      PUID: "1000"
      PGID: "1000"
    restart: always
    ports:
      - "7878:7878"
    volumes:
      - /media/d:/media/d:rw
      - /media/e:/media/e:rw
      - ${APPDATA_PATH}/radarr:/config
      - /home/${USERNAME}/storage:/storage

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:    
      TZ: "${TZ}"
      PUID: "1000"
      PGID: "1000"
    restart: always
    ports:
      - "8989:8989"
    volumes:
      - /media/d:/media/d:rw
      - /media/e:/media/e:rw
      - ${APPDATA_PATH}/sonarr:/config
      - /home/${USERNAME}/storage:/storage

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=1000
      - GUID=1000
      - UN_QUIET=false
      - UN_DEBUG=false
      - UN_ERROR_STDERR=false
      - UN_LOG_QUEUES=1m
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - UN_ACTIVITY=false
      # Sonarr Config
      - UN_SONARR_0_URL=http://10.1.1.5:8989
      - UN_SONARR_0_API_KEY=1cc411e36a9c4158bbb780298ded862e
      # Radarr Config
      - UN_RADARR_0_URL=http://10.1.1.5:7878
      - UN_RADARR_0_API_KEY=c501b672c11d4a57a430b3782dd38407
      # Folder Config
      - UN_FOLDER_0_PATH=/media/e/_downloads/_applications
      - UN_FOLDER_0_MOVE_BACK=true
      - UN_FOLDER_1_PATH=/media/e/_downloads/_audiobooks
      - UN_FOLDER_1_MOVE_BACK=true
      - UN_FOLDER_2_PATH=/media/e/_downloads/_books
      - UN_FOLDER_2_MOVE_BACK=true
      - UN_FOLDER_3_PATH=/media/e/_downloads/_movies_manual
      - UN_FOLDER_3_MOVE_BACK=true
      - UN_FOLDER_4_PATH=/media/e/_downloads/_music
      - UN_FOLDER_4_MOVE_BACK=true
      - UN_FOLDER_5_PATH=/media/e/_downloads/_tv_shows_manual
      - UN_FOLDER_5_MOVE_BACK=true
      - UN_FOLDER_6_PATH=/media/e/_downloads/_unsort
      - UN_FOLDER_6_MOVE_BACK=true

    volumes:
      - /media/e/_downloads:/downloads
      - /media/e:/media/e

  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    environment:
      PUID: "1000"
      PGID: "1000"
    restart: always
    ports:
      - "19200:5000"
    volumes:
      - ${APPDATA_PATH}/fileflows:/app/Data:rw
      - /home/${USERNAME}/storage:/storage:rw
      - /media/d:/media/d:rw
      - /media/e:/media/e:rw
      - /media/f:/media/f:rw

  watchtower:
    container_name: watchtower
    image: ghcr.io/containrrr/watchtower:latest
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      TZ: America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/${USERNAME}/storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped 